FROM node:12.17.0

EXPOSE 3003 3004 8083
COPY ["./package.json", "./package-lock.json", "./.eslintrc.js", "./.eslintignore", "./.babelrc", "./browserslist", "./.stylelintrc", "/app/"]

WORKDIR /app

VOLUME "/app/src"

RUN npm i --quiet

CMD npm run development
